version: "2"
services:
  reverse-proxy:
    container_name: reverse-proxy
    build:
      context: nginx/
      dockerfile : Dockerfile
    image: reverse-proxy:latest
    ports:
      - 80:80
    depends_on:
      - data-server
  data-server:
    container_name: data-server
    build:
      context: backend/testhelper/
      dockerfile: Dockerfile
    image: data-server:latest
    ports:
      - 8081:8081
    expose:
      - 8081
    environment:
      - AWS_PROFILE=test-helper
    volumes:
      - ~/.aws/:/root/.aws/:ro